name: Verify Gateway Marketplace Deployment on dev

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'chart/**'
      - 'schema.yaml'
      - 'dev.Dockerfile'
      - 'VERSION'
  repository_dispatch:
    types: [ verify-gateway ]
permissions:
  contents: read
  id-token: write

jobs:
  verify-marketplace:
    runs-on: virtru-scale-set-runner

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Authenticate to Google Cloud"
        id: "gcp-auth"
        uses: google-github-actions/auth@v2 # v2.1.5
        with:
          workload_identity_provider: "projects/1053957112592/locations/global/workloadIdentityPools/github-actions-oidc-pool/providers/github-actions-oidc-provider"
          service_account: "github-actions-sa@prj-infra-automation-ktbz.iam.gserviceaccount.com"
          token_format: "access_token"

      - name: "Setup gcloud CLI"
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'kubectl'

      - name: "Docker login to Artifact Registry"
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcp-auth.outputs.access_token }}

      - name: "Connect to GKE Cluster"
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: hg-dev-green

      - name: "Install mpdev"
        run: |
          curl -L -o mpdev.tar.gz https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/releases/download/v0.11.8/mpdev_linux_amd64.tar.gz
          tar -xzvf mpdev.tar.gz
          chmod +x mpdev
          sudo mv mpdev /usr/local/bin/

      - name: "Update Helm dependencies"
        run: |
          cd chart/gateway
          helm dependency update
          cd -

      - name: "Set version variables"
        run: |
          VERSION=$(cat VERSION)
          echo "TAG=${VERSION}" >> $GITHUB_ENV
          echo "DEPLOYER_VERSION=$(echo ${VERSION} | cut -d'.' -f 1-2)" >> $GITHUB_ENV
          echo "REGISTRY=us-east4-docker.pkg.dev/prj-hosted-gateway-dev-qvec/gateway/gateway" >> $GITHUB_ENV

      - name: "Build deployer image"
        uses: docker/build-push-action@v5 # v4.6.0
        with:
          context: .
          file: dev.Dockerfile
          push: true
          build-args: |
            TAG=${{ env.TAG }}
            REGISTRY=${{ env.REGISTRY }}
          tags: ${{ env.REGISTRY }}/deployer:${{ env.DEPLOYER_VERSION }}
          platforms: linux/amd64

      - name: "Install Application CRD"
        run: |
          kubectl apply -f "https://raw.githubusercontent.com/GoogleCloudPlatform/marketplace-k8s-app-tools/master/crd/app-crd.yaml"

      - name: "Run marketplace verification"
        run: |
          export MPDEV_VERIFY_TIMEOUT=600 # 10 minutes

          mpdev verify --deployer="${REGISTRY}/deployer:${DEPLOYER_VERSION}" --verbose

      - name: "Cleanup verification resources"
        if: always()
        run: |
          kubectl get ns -l app.kubernetes.io/name=apptest -o name | xargs -r kubectl delete --wait=false
