apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-{{ .Chart.Name }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "billing.selectorLabels" . | nindent 6 }}
  # Use a single replica. Multiple replicas may cause duplicate billing.
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "billing.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ubbagent
          image: {{ .Values.ubbagentImage }}
          env:
            - name: AGENT_CONFIG_FILE
              value: "/etc/ubbagent/config.yaml"
            - name: AGENT_LOCAL_PORT
              value: "4567"
            - name: AGENT_ENCODED_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.reportingSecret }}
                  key: reporting-key
            - name: AGENT_CONSUMER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.reportingSecret }}
                  key: consumer-id
            - name: ENTITLEMENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.reportingSecret }}
                  key: entitlement-id
          volumeMounts:
            - name: ubbagent-config
              mountPath: /etc/ubbagent
        - name: billing-helper-{{ .Chart.Name }}
          image: alpine:latest
          # This container runs a curl command on infinite loop. The curl posts usage data to ubbagent.
          # see https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/billing-integration.md#sending-usage-reports
          # Inputs:
          #  .Values.pricingPlan is from a pulldown/enum on the config page. It corresponds to the metric names.
          #     Example: gateway___gmail_encryption__per_user_
          #  .Values.numberOfLicenses is also from the config page.
          #     The customer enters the number of licenses for their subscription.
          command:
          - "/bin/sh"
          - "-c"
          - |
            set -x
            apk add curl
            echo "Starting billing helper. pricing plan: {{ .Values.pricingPlan }} ; licenses {{ .Values.numberOfLicenses }}" >&2
            # Users divided by 320 reporting windows:
            userfraction="0$( echo "scale=8;{{ .Values.numberOfLicenses }}/320" | bc)"

            while true
            do
              starttimestamp="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
              echo "Start Timestamp: ${starttimestamp}" >&2
              # Interval of 4.5 minutes minimizes rounding error because it divides to finite number of decimals: 0.003125
              sleep 270
              # report a time range from the start of the current hour, to the end of the current hour
              endtimestamp="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
              echo "End Timestamp: ${starttimestamp}" >&2

              # Number of licensed users, divided by 320 (24 hrs/320 = 4.5 minutes)
              # By reporting this fraction every hour, each month the cumulative total is the monthly bill.
              # using "bc" for calculation because shell only handles integers
              postbody="{\"name\":\"{{ .Values.pricingPlan }}\", \"startTime\": \"$starttimestamp\",\"endTime\": \"$endtimestamp\",\"value\": { \"DoubleValue\": $userfraction } }"
              echo "${postbody}" >&2
              curl -X POST -d "${postbody}" "http://localhost:4567/report"
            done
      volumes:
      - name: ubbagent-config
        configMap:
          name: ubbagent-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
